alter table __CTS_AccessProfile
add 
InsideSalesOverdueOrders bit null,
InsideSalesTurnoverCurrentWeek bit null,
InsideSalesTotalUnbookedOrders bit null,
InsideSalesMinimumStockEvaluation bit null,

InsideSalesOverdueOrdersTable bit null,
InsideSalesTotalUnbookedOrdersTable bit null,
InsideSalesMinimumStockEvaluationTable bit null