using Org.BouncyCastle.Asn1.Ocsp;
using Psz.Core.BaseData.Models.Article.ROH.OfferRequests;
using Psz.Core.Common.Models;
using Psz.Core.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Psz.Core.BaseData.Handlers.ROH.OfferRequests;

public class GenerateEMailForOfferRequestByUIHandler: IHandle<Identity.Models.UserModel, ResponseModel<List<OfferRequestEMail>>>
{
	private Identity.Models.UserModel _user { get; set; }
	private string _data { get; set; }
	public GenerateEMailForOfferRequestByUIHandler(Identity.Models.UserModel user, string RequestUI)
	{
		this._user = user;
		this._data = RequestUI;
	}

	public ResponseModel<List<OfferRequestEMail>> Handle()
	{
		var botransaction = new Infrastructure.Services.Utils.TransactionsManager();

		try
		{


			var validationResponse = this.Validate();
			if(!validationResponse.Success)
			{
				return validationResponse;
			}
			var offerfamily = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUI(_data);

			var offerrequestsPerSupplier = new List<OfferRequestPerSupplierModel>();

			var uniqueSuppliers = offerfamily.Select(x => x.SupplierId).Distinct().ToList();

			var offerRequestsSlicedUponUniqueSuppliers = new List<OfferRequestPerSupplierModel>();

			foreach(var item in uniqueSuppliers)
			{
				var uniquePerSupplierItem = new OfferRequestPerSupplierModel();
				uniquePerSupplierItem.SupplierId = item;
				var requestforthisSupplier = offerfamily.Where(x => x.SupplierId == item).ToList();
				var dataForTheEmail = requestforthisSupplier.Select(x => new MaterialRequestModel() { MatNr = x.ManufactuerNumber, Jahresmenge = x.YearlyQuantity, Hersteller = x.SupplierName, unit = x.unit }).ToList();
				uniquePerSupplierItem.OfferRequests.AddRange(dataForTheEmail);
				offerRequestsSlicedUponUniqueSuppliers.Add(uniquePerSupplierItem);
			}
			var restoreturn = new List<OfferRequestEMail>();

			botransaction.beginTransaction();
			int updatedSupplierId = -1;
			foreach(var item in offerRequestsSlicedUponUniqueSuppliers)
			{
				var email = new OfferRequestEMail();
				var fetchedIds = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUIAndSupplierID(_data, item.SupplierId);
				email.Ids = fetchedIds.Select(x => x.Id).ToList();
				// get Default recipient 
				email.Recipient = fetchedIds.First().SupplierContactEmail;
				// get Default CC EMAIL 
				email.CCEmail = fetchedIds.First().CCEmail;

				email.EmailSubject = fetchedIds.First().EmailSubject;
				// use the quantites and material to generate the needed Data for the email body . 
				var dataforemail = item.OfferRequests.Select(x => new Infrastructure.Services.Email.Models.MaterialRequestbaseModel() { Hersteller = x.Hersteller, MatNr = x.MatNr, Jahresmenge = x.Jahresmenge, Bez = x.Bez }).ToList();

				email.EmailContent = GenerateEmailBasedOnDefaultSupplierLanguage(item.SupplierId ?? -1, fetchedIds.First().ProjectName, fetchedIds.First().EndCustomer);
				email.multipleSuppliers = uniqueSuppliers.Count() > 1 ? true : false;

				//return the request UI
				email.RequestUI = _data;
				restoreturn.Add(email);
				if(updatedSupplierId != item.SupplierId)
				{
					var result = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.UpdateAutoGeneratedEmailContent(_data, item.SupplierId ?? -1, email.EmailContent, botransaction.connection, botransaction.transaction);
				}
				updatedSupplierId = item.SupplierId ?? 0;
			}
			if(botransaction.commit())
			{
				return ResponseModel<List<OfferRequestEMail>>.SuccessResponse(restoreturn);
			}
			else
			{
				return ResponseModel<List<OfferRequestEMail>>.FailureResponse("Saving Data Failed !");
			}

		} catch(Exception e)
		{
			botransaction.rollback();
			Infrastructure.Services.Logging.Logger.Log(e);
			throw;
		}
	}
	private string GenerateEmailBasedOnDefaultSupplierLanguage(int supplierID,string Project, string Customer)
	{

		if(supplierID == -1)
			return string.Empty;
		var fetchedIds = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetDefaultLanguageForSupplier(supplierID);
		if(fetchedIds is null || fetchedIds.ID is null || fetchedIds.ID == 0)
			fetchedIds = new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.SupplierDefaultLanguageEntity() { ID = 4 };

		var userEntity = Infrastructure.Data.Access.Tables.COR.UserAccess.Get(_user.Id);

		var emailBody = fetchedIds.ID switch
		{
			1 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialRequestEmailAsHtmlContentWithoutMaterialDataEN(_user.Name, userEntity.TelephoneIP, _user.Email, Project, Customer),
			2 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialRequestEmailAsHtmlContentWithoutMaterialDataFR(_user.Name ,userEntity.TelephoneIP, _user.Email, Project, Customer),
			3 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialRequestEmailAsHtmlContentWithoutMaterialDataES(_user.Name, userEntity.TelephoneIP, _user.Email, Project, Customer),
			_ => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialRequestEmailAsHtmlContentWithoutMaterialDataDE(_user.Name, userEntity.TelephoneIP, _user.Email, Project, Customer)
		};
		return emailBody;
	}
	public ResponseModel<List<OfferRequestEMail>> Validate()
	{
		if(this._user == null /*|| this._user.Access.____*/)
		{
			return ResponseModel<List<OfferRequestEMail>>.AccessDeniedResponse();
		}
		return ResponseModel<List<OfferRequestEMail>>.SuccessResponse();
	}
}