using Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests;
using Org.BouncyCastle.Asn1.Ocsp;
using Psz.Core.BaseData.Enums;
using Psz.Core.BaseData.Helpers;
using Psz.Core.BaseData.Models.Article.ROH.OfferRequests;
using Psz.Core.BaseData.Models.ROH;
using Psz.Core.Common;
using Psz.Core.Common.Models;
using Psz.Core.SharedKernel.Interfaces;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static iText.StyledXmlParser.Jsoup.Select.Evaluator;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Psz.Core.BaseData.Handlers.ROH.OfferRequests
{
	public class SendOfferRequestEmailToSuppliersIHandler: IHandle<Identity.Models.UserModel, ResponseModel<int>>
	{
		private Identity.Models.UserModel _user { get; set; }
		private List<int> _data { get; set; }
		public SendOfferRequestEmailToSuppliersIHandler(Identity.Models.UserModel user, List<int> Ids)
		{
			this._user = user;
			this._data = Ids;
		}
		public ResponseModel<int> Handle()
		{
			var botransaction = new Infrastructure.Services.Utils.TransactionsManager();

			try
			{

				var result = new ResponseModel<int>();
				var validationResponse = this.Validate();
				if(!validationResponse.Success)
				{
					return validationResponse;
				}
				// fetch offers from Db
				var IdsToUpdateTheirStatus = new List<int>();
				var fetchedOffers = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(_data);
				var uniqueSuppliers = fetchedOffers.Select(x => x.SupplierId).Distinct().ToList();
				var requestUI = fetchedOffers.Select(x => x.RequestUI).Distinct().ToList();

				if(requestUI is null || requestUI.Count == 0 || (requestUI is not null && requestUI.Count > 1))
					return ResponseModel<int>.FailureResponse("Can Not send Different Offers at once !");


				foreach(var item in uniqueSuppliers)
				{
					var AlloffersGroupedBySuppliers = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUIAndSupplierIDEligibleToBeSent(requestUI.First(), item);
					var offersGroupedBySuppliers = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUIAndSupplierIDEligibleToBeSent(requestUI.First(), item).First();

					if(AlloffersGroupedBySuppliers is null || AlloffersGroupedBySuppliers.Count == 0)
						throw new InvalidOperationException("there is no email in the database or the email already sent or the offer is cancelled");
					var OffersIdsToUpdate = AlloffersGroupedBySuppliers.Select(x => x.Id).Distinct().ToList();
					#region validate Email Adresses

					int key = 1;
					bool InvalidData = false;
					bool InvalidCCS = false;
					// VALIDATE SUPPLIER ADRESS
					var invalidEmail = IsValidEmailAdress(offersGroupedBySuppliers.SupplierContactEmail);

					if(invalidEmail != string.Empty || invalidEmail.Length > 0)
					{
						result.Errors.Add(new ResponseModel<int>.ResponseError() { Key = $"{key}", Value = $"Invalid Adress EMail :{invalidEmail}" });
						key++;
						InvalidData = true;
					}
					//
					// validate CCs
					string invalidCC = "";
					List<string> AdditionalCCs = new List<string>() { offersGroupedBySuppliers.CCEmail };
					if(offersGroupedBySuppliers.AdditionalCC is not null && offersGroupedBySuppliers.AdditionalCC != string.Empty && offersGroupedBySuppliers.AdditionalCC.Length > 5)
					{
						AdditionalCCs.AddRange(SplitAdditionalCCs(offersGroupedBySuppliers.AdditionalCC));

						foreach(var emailcc in AdditionalCCs)
						{
							invalidCC = IsValidEmailAdress(emailcc);
							if(invalidCC != string.Empty || invalidCC.Length > 0)
							{
								result.Errors.Add(new ResponseModel<int>.ResponseError() { Key = $"{key}", Value = $"Invalid Adress EMail in CC :{invalidCC}" });
								key++;
								InvalidCCS = true;
							}
						}
					}

					if(InvalidData || InvalidCCS)
						return result;
					#endregion
					#region Validate EmailsContent

					var emailContent = (offersGroupedBySuppliers.LatestEmailContent == null || offersGroupedBySuppliers.LatestEmailContent == string.Empty) ? offersGroupedBySuppliers.AutogeneratedEmailContent : offersGroupedBySuppliers.LatestEmailContent;

					var dataforEmail = Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(AlloffersGroupedBySuppliers);
					emailContent = Infrastructure.Services.Helpers.EmailHelper.AddMaterialTableToTheEmail(dataforEmail, emailContent);
					if(!IsValidEmailContent(emailContent))
					{
						result.Errors.Add(new ResponseModel<int>.ResponseError() { Key = $"{key}", Value = $"Invalid EMail Adress  :{emailContent}" });
						key++;
					}

					#endregion
					#region SendEmailsToSuppliers
					botransaction.beginTransaction();
					#region Get Email Attachments
					List<Infrastructure.Services.Files.Models.FileContent> data = null;

					var attchments = GetAttachmentsIds(AlloffersGroupedBySuppliers.Select(x => x.Id).Distinct().ToList());
					if(attchments is not null && attchments.Count > 0)
					{
						data = new List<Infrastructure.Services.Files.Models.FileContent>();
						var FileIds = attchments.Select(x => (int)x.FileId ).ToList();
						foreach(var FileId in FileIds)
						{
							
							data.Add(GetAttachment(FileId));
						}
					}
					#endregion
					
					var Sent = SendEmailToSuppliers(offersGroupedBySuppliers.EmailSubject, emailContent, new List<string>() { offersGroupedBySuppliers.SupplierContactEmail }, ccs: AdditionalCCs, data);
					if(Sent)
					{
						IdsToUpdateTheirStatus.AddRange(OffersIdsToUpdate);
					}
					#endregion
				}
				if(IdsToUpdateTheirStatus.Count() > 0)
				{
					Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.UpdateOfferRequestEmailStatus(IdsToUpdateTheirStatus, true, botransaction.connection, botransaction.transaction);
					Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.UpdateOfferRequestOnGoingStatusForMultipleOffers(IdsToUpdateTheirStatus, OfferRequestsManager.GenerateRequestStatus(OfferRequestStatus.sent, _user), botransaction.connection, botransaction.transaction);
				}
				// Logs
				var LogSavingResult = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsAccess.InsertWithTransaction(GenerateLogs(_data, IdsToUpdateTheirStatus), botransaction.connection, botransaction.transaction);

				if(botransaction.commit())
				{
					return ResponseModel<int>.SuccessResponse();
				}
				else
				{
					return ResponseModel<int>.FailureResponse("Saving Data Failed !");
				}

			} catch(Exception e)
			{
				botransaction.rollback();
				Infrastructure.Services.Logging.Logger.Log(e);
				throw;
			}
		}
		public ResponseModel<int> Validate()
		{
			if(this._user == null /*|| this._user.Access.____*/)
			{
				return ResponseModel<int>.AccessDeniedResponse();
			}
			return ResponseModel<int>.SuccessResponse();
		}
		#region Emails Validation and Processing 
		private static List<string> SplitAdditionalCCs(string str)
		{
			if(string.IsNullOrEmpty(str))
			{
				return new List<string>();
			}
			return str.Split(';').ToList();
		}
		/*private bool SendEmailToSuppliers(string Subject, string content, List<string> adresses, List<string> ccs, Infrastructure.Services.Files.Models.FileContent attachment)
		{
			if(attachment is null)
			{
				return Module.EmailingService.SendEmailAsync(Subject, content, toAddresses: adresses, null, toAddressesCC: ccs).Result;
			}
			else
			{
				// Convert the FileContent to a KeyValuePair<string, System.IO.Stream>
				var attachments = new List<KeyValuePair<string, System.IO.Stream>>
		{
			new KeyValuePair<string, System.IO.Stream>(
				attachment.FileName + attachment.FileExtension,
				new System.IO.MemoryStream(attachment.FileBytes))
		};

				return Module.EmailingService.SendEmailAsync(Subject, content, toAddresses: adresses, attachments: attachments, toAddressesCC: ccs).Result;
			}
		}*/
		private List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsEntity> GetAttachmentsIds(List<int> OffersIds)
		{
			try
			{
				return Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsAccess.GetAttachmentsPerOffers(OffersIds);

			} catch(Exception e)
			{
				Infrastructure.Services.Logging.Logger.Log(e);
			}
			return new List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsEntity>();

		}
		private bool SendEmailToSuppliers(string Subject, string content, List<string> adresses, List<string> ccs, List<Infrastructure.Services.Files.Models.FileContent> attachments)
		{
			if(attachments == null || attachments.Count == 0)
			{
				return Module.EmailingService.SendEmailAsync(Subject, content, toAddresses: adresses, toAddressesCC: ccs).Result;
			}
			else
			{
				var attachmentList = new List<KeyValuePair<string, System.IO.Stream>>();

				foreach(var attachment in attachments)
				{
					attachmentList.Add(new KeyValuePair<string, System.IO.Stream>(
						attachment.FileName + attachment.FileExtension,
						new System.IO.MemoryStream(attachment.FileBytes)));
				}
				return Module.EmailingService.SendEmailAsync(Subject, content, toAddresses: adresses, attachments: attachmentList, toAddressesCC: ccs).Result;
			}
		}
		public string IsValidEmailAdress(string adresses)
		{

			if(!Infrastructure.Services.Email.Helpers.IsValidEmail(adresses))
			{
				return adresses;
			}

			return string.Empty;
		}
		private bool IsValidEmailContent(string content)
		{
			return !(string.IsNullOrEmpty(content) || string.IsNullOrWhiteSpace(content));
		}
		//
		private Infrastructure.Services.Files.Models.FileContent GetAttachment(int FileId)
		{
			try
			{
				return Program.FilesManager.GetFile(FileId);

			} catch(Exception e)
			{
				Infrastructure.Services.Logging.Logger.Log(e);
			}
			return null;
		}
		#endregion
		#region Logs Generation
		private List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity> GenerateLogs(List<int> Ids,List<int> IdsToUpdateTheirStatus)
		{
			var logs = new List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity>();
			var offerEnities = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(Ids);

			foreach(var Id in offerEnities)
			{
				if(IdsToUpdateTheirStatus.Contains(Id.Id))
				{
					logs.Add(
										new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
										{
											LastUpdateUserId = _user.Id,
											LastUpdateUsername = _user.Username,
											LastUpdateTime = DateTime.Now,
											LastUpdateUserFullName = _user.Name,
											LogDescription = $"The Offer request Email  has been Sent to  the supplier",
											LogObjectId = Id.Id,
											ManufacturerNumber = Id.ManufactuerNumber,
											SupplierContactName = Id.SupplierContactName,
											LogObject = "BSD Offer Request"
										}
										);
				}
				else
				{
					logs.Add(
										new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
										{
											LastUpdateUserId = _user.Id,
											LastUpdateUsername = _user.Username,
											LastUpdateTime = DateTime.Now,
											LastUpdateUserFullName = _user.Name,
											LogDescription = $"The Offer request Email  Failed to be Delivered ",
											LogObjectId = Id.Id,
											ManufacturerNumber = Id.ManufactuerNumber,
											SupplierContactName = Id.SupplierContactName,
											LogObject = "BSD Offer Request"
										}
										);
				}
				
			}
			return logs;
		}
		#endregion
	}
}
