using System;
using System.Collections.Generic;
using System.Data;

namespace Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests;

public class ArticleOfferRequestsEntity
{
	public string AdditionalCC { get; set; }
	public DateTime? AngebotDatum { get; set; }
	public string attachment { get; set; }
	public string AutogeneratedEmailContent { get; set; }
	public string CCEmail { get; set; }
	public DateTime? ClosedDate { get; set; }
	public int? ClosedUserId { get; set; }
	public string ClosedUserName { get; set; }
	public string CountryOfOrigin { get; set; }
	public DateTime? CreatedDate { get; set; }
	public int? CreatedUserId { get; set; }
	public string CreatedUserName { get; set; }
	public decimal? CustomQuantity { get; set; }
	public string CustomTariffNumber { get; set; }
	public int? DeliveryTime { get; set; }
	public string EmailId { get; set; }
	public bool? EmailStatus { get; set; }
	public string EmailSubject { get; set; }
	public string EndCustomer { get; set; }
	public decimal? ExportWeight { get; set; }
	public string Feedback { get; set; }
	public int? FileId { get; set; }
	public decimal? Graduatedprice1 { get; set; }
	public decimal? Graduatedprice2 { get; set; }
	public decimal? Graduatedprice3 { get; set; }
	public int? Graduatedquantity1 { get; set; }
	public int? Graduatedquantity2 { get; set; }
	public int? Graduatedquantity3 { get; set; }
	public int Id { get; set; }
	public string LatestEmailContent { get; set; }
	public string ManufactuerNumber { get; set; }
	public decimal? MinOrderQuantity { get; set; }
	public DateTime? OfferDate { get; set; }
	public string OfferNumber { get; set; }
	public string OfferRequestArticleDescription { get; set; }
	public string ongoingStatus { get; set; }
	public int? PackagingUnit { get; set; }
	public DateTime? PriceExpiryDate { get; set; }
	public string ProjectName { get; set; }
	public bool? RequestStatus { get; set; }
	public string RequestUI { get; set; }
	public DateTime? SentDate { get; set; }
	public int? SentUserId { get; set; }
	public string SentUserName { get; set; }
	public string SupplierContactEmail { get; set; }
	public string SupplierContactName { get; set; }
	public int? SupplierId { get; set; }
	public string SupplierName { get; set; }
	public string unit { get; set; }
	public decimal? UnitPrice { get; set; }
	public decimal? YearlyQuantity { get; set; }

	public ArticleOfferRequestsEntity() { }

	public ArticleOfferRequestsEntity(DataRow dataRow)
	{
		AdditionalCC = (dataRow["AdditionalCC"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["AdditionalCC"]);
		AngebotDatum = (dataRow["AngebotDatum"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["AngebotDatum"]);
		attachment = (dataRow["attachment"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["attachment"]);
		AutogeneratedEmailContent = (dataRow["AutogeneratedEmailContent"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["AutogeneratedEmailContent"]);
		CCEmail = (dataRow["CCEmail"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["CCEmail"]);
		ClosedDate = (dataRow["ClosedDate"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["ClosedDate"]);
		ClosedUserId = (dataRow["ClosedUserId"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["ClosedUserId"]);
		ClosedUserName = (dataRow["ClosedUserName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["ClosedUserName"]);
		CountryOfOrigin = (dataRow["CountryOfOrigin"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["CountryOfOrigin"]);
		CreatedDate = (dataRow["CreatedDate"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["CreatedDate"]);
		CreatedUserId = (dataRow["CreatedUserId"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["CreatedUserId"]);
		CreatedUserName = (dataRow["CreatedUserName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["CreatedUserName"]);
		CustomQuantity = (dataRow["CustomQuantity"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["CustomQuantity"]);
		CustomTariffNumber = (dataRow["CustomTariffNumber"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["CustomTariffNumber"]);
		DeliveryTime = (dataRow["DeliveryTime"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["DeliveryTime"]);
		EmailId = (dataRow["EmailId"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["EmailId"]);
		EmailStatus = (dataRow["EmailStatus"] == System.DBNull.Value) ? (bool?)null : Convert.ToBoolean(dataRow["EmailStatus"]);
		EmailSubject = (dataRow["EmailSubject"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["EmailSubject"]);
		EndCustomer = (dataRow["EndCustomer"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["EndCustomer"]);
		ExportWeight = (dataRow["ExportWeight"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["ExportWeight"]);
		Feedback = (dataRow["Feedback"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["Feedback"]);
		FileId = (dataRow["FileId"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["FileId"]);
		Graduatedprice1 = (dataRow["Graduatedprice1"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["Graduatedprice1"]);
		Graduatedprice2 = (dataRow["Graduatedprice2"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["Graduatedprice2"]);
		Graduatedprice3 = (dataRow["Graduatedprice3"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["Graduatedprice3"]);
		Graduatedquantity1 = (dataRow["Graduatedquantity1"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["Graduatedquantity1"]);
		Graduatedquantity2 = (dataRow["Graduatedquantity2"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["Graduatedquantity2"]);
		Graduatedquantity3 = (dataRow["Graduatedquantity3"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["Graduatedquantity3"]);
		Id = Convert.ToInt32(dataRow["Id"]);
		LatestEmailContent = (dataRow["LatestEmailContent"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["LatestEmailContent"]);
		ManufactuerNumber = (dataRow["ManufactuerNumber"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["ManufactuerNumber"]);
		MinOrderQuantity = (dataRow["MinOrderQuantity"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["MinOrderQuantity"]);
		OfferDate = (dataRow["OfferDate"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["OfferDate"]);
		OfferNumber = (dataRow["OfferNumber"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["OfferNumber"]);
		OfferRequestArticleDescription = (dataRow["OfferRequestArticleDescription"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["OfferRequestArticleDescription"]);
		ongoingStatus = (dataRow["ongoingStatus"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["ongoingStatus"]);
		PackagingUnit = (dataRow["PackagingUnit"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["PackagingUnit"]);
		PriceExpiryDate = (dataRow["PriceExpiryDate"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["PriceExpiryDate"]);
		ProjectName = (dataRow["ProjectName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["ProjectName"]);
		RequestStatus = (dataRow["RequestStatus"] == System.DBNull.Value) ? (bool?)null : Convert.ToBoolean(dataRow["RequestStatus"]);
		RequestUI = (dataRow["RequestUI"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["RequestUI"]);
		SentDate = (dataRow["SentDate"] == System.DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(dataRow["SentDate"]);
		SentUserId = (dataRow["SentUserId"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["SentUserId"]);
		SentUserName = (dataRow["SentUserName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["SentUserName"]);
		SupplierContactEmail = (dataRow["SupplierContactEmail"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["SupplierContactEmail"]);
		SupplierContactName = (dataRow["SupplierContactName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["SupplierContactName"]);
		SupplierId = (dataRow["SupplierId"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["SupplierId"]);
		SupplierName = (dataRow["SupplierName"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["SupplierName"]);
		unit = (dataRow["unit"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["unit"]);
		UnitPrice = (dataRow["UnitPrice"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["UnitPrice"]);
		YearlyQuantity = (dataRow["YearlyQuantity"] == System.DBNull.Value) ? (decimal?)null : Convert.ToDecimal(dataRow["YearlyQuantity"]);
	}

	public ArticleOfferRequestsEntity ShallowClone()
	{
		return new ArticleOfferRequestsEntity
		{
			AdditionalCC = AdditionalCC,
			AngebotDatum = AngebotDatum,
			attachment = attachment,
			AutogeneratedEmailContent = AutogeneratedEmailContent,
			CCEmail = CCEmail,
			ClosedDate = ClosedDate,
			ClosedUserId = ClosedUserId,
			ClosedUserName = ClosedUserName,
			CountryOfOrigin = CountryOfOrigin,
			CreatedDate = CreatedDate,
			CreatedUserId = CreatedUserId,
			CreatedUserName = CreatedUserName,
			CustomQuantity = CustomQuantity,
			CustomTariffNumber = CustomTariffNumber,
			DeliveryTime = DeliveryTime,
			EmailId = EmailId,
			EmailStatus = EmailStatus,
			EmailSubject = EmailSubject,
			EndCustomer = EndCustomer,
			ExportWeight = ExportWeight,
			Feedback = Feedback,
			FileId = FileId,
			Graduatedprice1 = Graduatedprice1,
			Graduatedprice2 = Graduatedprice2,
			Graduatedprice3 = Graduatedprice3,
			Graduatedquantity1 = Graduatedquantity1,
			Graduatedquantity2 = Graduatedquantity2,
			Graduatedquantity3 = Graduatedquantity3,
			Id = Id,
			LatestEmailContent = LatestEmailContent,
			ManufactuerNumber = ManufactuerNumber,
			MinOrderQuantity = MinOrderQuantity,
			OfferDate = OfferDate,
			OfferNumber = OfferNumber,
			OfferRequestArticleDescription = OfferRequestArticleDescription,
			ongoingStatus = ongoingStatus,
			PackagingUnit = PackagingUnit,
			PriceExpiryDate = PriceExpiryDate,
			ProjectName = ProjectName,
			RequestStatus = RequestStatus,
			RequestUI = RequestUI,
			SentDate = SentDate,
			SentUserId = SentUserId,
			SentUserName = SentUserName,
			SupplierContactEmail = SupplierContactEmail,
			SupplierContactName = SupplierContactName,
			SupplierId = SupplierId,
			SupplierName = SupplierName,
			unit = unit,
			UnitPrice = UnitPrice,
			YearlyQuantity = YearlyQuantity
		};
	}
}
public class SupplierDefaultLanguageEntity
{
	public int? Nr { get; set; }
	public int? ID { get; set; }
	public string Sprache { get; set; }
	public SupplierDefaultLanguageEntity() { }
	public SupplierDefaultLanguageEntity(DataRow dataRow)
	{
		Sprache = (dataRow["Sprache"] == System.DBNull.Value) ? "" : Convert.ToString(dataRow["Sprache"]);
		Nr = (dataRow["Nr"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["Nr"]);
		ID = (dataRow["ID"] == System.DBNull.Value) ? (int?)null : Convert.ToInt32(dataRow["ID"]);
	}
}