using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Infrastructure.Data.Access.Tables.Logistics
{

	public class PlantBookingAccess
	{
		#region Default Methods
		#endregion

		#region Custom Methods
		public static int InsertWithBestellteArtikelTn(int LagerId, int? nrBestellteArtikel)
		{

			int response = int.MinValue;
			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			{
				sqlConnection.Open();
				var sqlTransaction = sqlConnection.BeginTransaction();


				string query = @"DECLARE @NewId TABLE ([Nummer Verpackung] INT);
								INSERT INTO [PSZ_Eingangskontrolle_TN]   
								(
								Aktiv,
                                [Datum],
								[LagerortID],
								[Bestellung-Nr],
								WE_Anzahl_VOH,
								WE_Datum_VOH,
								Eingangslieferscheinnr,
								Artikelnummer, 
								Menge,
								Gesamtmenge,
								Anzahl_Verpackungen,
								[Clock Number],
								Inspektor,   
								Kunde,   
								Prüfentscheid,
								Resultat,
								Prüfmenge,
								Prüftiefe,
								Geprüfte_Prüfmenge,
								WE_LS_VOH,
								MHDDatum 
								)      
								OUTPUT INSERTED.[Nummer Verpackung] INTO @NewId 
                                SELECT 
								0,
								GETDATE(), 
								@LagerId ,
								B.[Bestellung-Nr],BA.Anzahl,B.Datum,@nrBestellteArtikel ,
								A.Artikelnummer,Anzahl / 1,Anzahl,1,0,'-','-'   ,0,'-',   /*Prüfmenge*/  
								Anzahl / 1 * (        IIF(Prüftiefe_WE = 1, 1,
								IIF(Prüftiefe_WE = 2, 0.3,         
								IIF(Prüftiefe_WE = 3, 0.05, 0.01)            
								)        
								)    
								), 
								/*Prüftiefe*/ IIF(   Prüftiefe_WE = 1, 1,IIF(Prüftiefe_WE = 2, 0.3,IIF(Prüftiefe_WE = 3, 0.05, 0.01))), 
								0, 
								Eingangslieferscheinnr, 
								MhdDatumArtikel 
								FROM Bestellungen B INNER JOIN [bestellte Artikel] BA ON BA.[Bestellung-Nr] = B.Nr   
								INNER JOIN Artikel A ON A.[Artikel-Nr] = BA.[Artikel-Nr]  
								INNER JOIN Bestellnummern BE ON B.[Lieferanten-Nr] = BE.[Lieferanten-Nr] 
								AND A.[Artikel-Nr] = BE.[Artikel-Nr]   
								WHERE BA.nr = @nrBestellteArtikel
								SELECT [Nummer Verpackung] AS NewAutoGeneratedWiw FROM @NewId ";
				using(var sqlCommand = new SqlCommand(query, sqlConnection, sqlTransaction))
				{

					sqlCommand.Parameters.AddWithValue("nrBestellteArtikel", nrBestellteArtikel == null ? (object)DBNull.Value : nrBestellteArtikel);
					sqlCommand.Parameters.AddWithValue("LagerId", LagerId == 0 ? (object)DBNull.Value : LagerId);

					var result = DbExecution.ExecuteScalar(sqlCommand);
					response = result == null ? int.MinValue : int.TryParse(result.ToString(), out var insertedId) ? insertedId : int.MinValue;
				}
				sqlTransaction.Commit();

				return response;
			}
		}
		public static int InsertWithTransactionBestellteArtikelTn(int LagerId, int? nrBestellteArtikel, string inspector, string remarks, SqlConnection connection, SqlTransaction transaction)
		{
			string query = @"DECLARE @NewId TABLE ([Nummer Verpackung] INT);
								INSERT INTO [PSZ_Eingangskontrolle_TN]   
								(
								Aktiv,
                                [Datum],
								[LagerortID],
								[Bestellung-Nr],
								WE_Anzahl_VOH,
								WE_Datum_VOH,
								Eingangslieferscheinnr,
								Artikelnummer, 
								Menge,
								Gesamtmenge,
								Anzahl_Verpackungen,
								[Clock Number],
								Inspektor,   
								Kunde,   
								Prüfentscheid,
								Resultat,
								Prüfmenge,
								Prüftiefe,
								Geprüfte_Prüfmenge,
								WE_LS_VOH,
								MHDDatum 
								)      
								OUTPUT INSERTED.[Nummer Verpackung] INTO @NewId 
                                SELECT 
								0,
								GETDATE(), 
								@LagerId ,
								B.[Bestellung-Nr],BA.Anzahl,B.Datum,@nrBestellteArtikel ,
								A.Artikelnummer,Anzahl / 1,Anzahl,1,0,@inspector,'-'   ,0,@remarks,   /*Prüfmenge*/  
								Anzahl / 1 * (        IIF(Prüftiefe_WE = 1, 1,
								IIF(Prüftiefe_WE = 2, 0.3,         
								IIF(Prüftiefe_WE = 3, 0.05, 0.01)            
								)        
								)    
								), 
								/*Prüftiefe*/ IIF(   Prüftiefe_WE = 1, 1,IIF(Prüftiefe_WE = 2, 0.3,IIF(Prüftiefe_WE = 3, 0.05, 0.01))), 
								0, 
								Eingangslieferscheinnr, 
								MhdDatumArtikel 
								FROM Bestellungen B INNER JOIN [bestellte Artikel] BA ON BA.[Bestellung-Nr] = B.Nr   
								INNER JOIN Artikel A ON A.[Artikel-Nr] = BA.[Artikel-Nr]  
								INNER JOIN Bestellnummern BE ON B.[Lieferanten-Nr] = BE.[Lieferanten-Nr] 
								AND A.[Artikel-Nr] = BE.[Artikel-Nr]   
								WHERE BA.nr = @nrBestellteArtikel
								SELECT [Nummer Verpackung] AS NewAutoGeneratedWiw FROM @NewId ";
			using(var sqlCommand = new SqlCommand(query, connection, transaction))
			{
				sqlCommand.Parameters.AddWithValue("nrBestellteArtikel", nrBestellteArtikel == null ? (object)DBNull.Value : nrBestellteArtikel);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId == 0 ? (object)DBNull.Value : LagerId);
				sqlCommand.Parameters.AddWithValue("inspector", inspector == null ? "-" : inspector);
				sqlCommand.Parameters.AddWithValue("remarks", remarks == null ? "-" : remarks);
				var result = DbExecution.ExecuteScalar(sqlCommand);
				return result == null ? int.MinValue : int.TryParse(result.ToString(), out var insertedId) ? insertedId : int.MinValue;
			}
		}
		public static int InsertWithTransactionTransferBestellteArtikelTn(int AnzahlNach,int LagerId, int? nrBestellteArtikel, int? LagerbewegungenId, SqlConnection connection, SqlTransaction transaction)
		{
			string query = @"DECLARE @NewId TABLE ([Nummer Verpackung] INT);
								INSERT INTO [PSZ_Eingangskontrolle_TN]   
								(
								Aktiv,
			                    [Datum],
								[LagerortID],
								[Bestellung-Nr],
								WE_Anzahl_VOH,
								WE_Datum_VOH,
								Eingangslieferscheinnr,
								Artikelnummer, 
								Menge,
								Gesamtmenge,
								Anzahl_Verpackungen,
								[Clock Number],
								Inspektor,   
								Kunde,   
								Prüfentscheid,
								Resultat,
								Prüfmenge,
								Prüftiefe,
								Geprüfte_Prüfmenge,
								WE_LS_VOH,
								MHDDatum 
								)      
								OUTPUT INSERTED.[Nummer Verpackung] INTO @NewId 
			                    SELECT 
								0,
								GETDATE(), 
								@LagerId ,
							    B.[Bestellung-Nr], l.Anzahl_nach ,B.Datum,@nrBestellteArtikel ,
								A.Artikelnummer,  ISNULL(@AnzahlNach,0) - isnull(l.receivedQuantity,0) / 1 ,@AnzahlNach,1,0,'-','-'   ,0,'-',   /*Prüfmenge*/  
								l.Anzahl / 1 * (        IIF(Prüftiefe_WE = 1, 1,
								IIF(Prüftiefe_WE = 2, 0.3,         
								IIF(Prüftiefe_WE = 3, 0.05, 0.01)                        
								)        
								)    
								), 
								/*Prüftiefe*/ IIF(   Prüftiefe_WE = 1, 1,IIF(Prüftiefe_WE = 2, 0.3,IIF(Prüftiefe_WE = 3, 0.05, 0.01))), 
								0, 
								Eingangslieferscheinnr, 
								MhdDatumArtikel 
								FROM Bestellungen B INNER JOIN [bestellte Artikel] BA ON BA.[Bestellung-Nr] = B.Nr   
								INNER JOIN Artikel A ON A.[Artikel-Nr] = BA.[Artikel-Nr]  
								INNER JOIN Bestellnummern BE ON B.[Lieferanten-Nr] = BE.[Lieferanten-Nr] 
								INNER JOIN  Lagerbewegungen_Artikel l on l.WereingangId=BA.Nr
								AND A.[Artikel-Nr] = BE.[Artikel-Nr]   
								WHERE L.id = @LagerbewegungenId
								SELECT [Nummer Verpackung] AS NewAutoGeneratedWiw FROM @NewId ";
			using(var sqlCommand = new SqlCommand(query, connection, transaction))
			{
				sqlCommand.Parameters.AddWithValue("nrBestellteArtikel", nrBestellteArtikel == null ? (object)DBNull.Value : nrBestellteArtikel);
				sqlCommand.Parameters.AddWithValue("LagerbewegungenId", LagerbewegungenId == null ? (object)DBNull.Value : LagerbewegungenId);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId == 0 ? (object)DBNull.Value : LagerId);
				sqlCommand.Parameters.AddWithValue("AnzahlNach", AnzahlNach == 0 ? (object)DBNull.Value : AnzahlNach);
				var result = DbExecution.ExecuteScalar(sqlCommand);
				return result == null ? int.MinValue : int.TryParse(result.ToString(), out var insertedId) ? insertedId : int.MinValue;
			}
		}
		public static int InsertWithArtikelNummerTn(int LagerId, string? ArtikelNummer, DateTime? MHDDatum, string inspector, string remarks, SqlConnection connection, SqlTransaction transaction)
		{
			string query = @"DECLARE @NewId TABLE([Nummer Verpackung] INT);
								INSERT INTO[PSZ_Eingangskontrolle_TN]
								(
								Aktiv,
								[Datum], 
								[LagerortID], 
								[Bestellung-Nr], 
								WE_Anzahl_VOH, 
								WE_Datum_VOH, 
								Eingangslieferscheinnr, 
								ArtikelNummer, 
								Menge, 
								Gesamtmenge, Anzahl_Verpackungen, 
								[Clock Number], 
								Inspektor, 
								Kunde, 
								Prüfentscheid, Resultat, 
								Prüfmenge, 
								Prüftiefe, 
								Geprüfte_Prüfmenge, 
								WE_LS_VOH, 
								MHDDatum
								)
								OUTPUT 
								INSERTED.[Nummer Verpackung] INTO @NewId 
								SELECT 
								0,
								GETDATE(), 
								@LagerId,
								0,
								0,
								'',
								0,
								@ArtikelNummer,
								0,
								0,
								1,
								0,
								@inspector,
								'-',
								0,
								@remarks,
								0,
								1,
								0,
								null,
								@MHDDatum 
								SELECT[Nummer Verpackung] AS NewAutoGeneratedWiw FROM @NewId";
			using(var sqlCommand = new SqlCommand(query, connection, transaction))
			{
				sqlCommand.Parameters.AddWithValue("ArtikelNummer", ArtikelNummer == null ? (object)DBNull.Value : ArtikelNummer);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId == 0 ? (object)DBNull.Value : LagerId);
				sqlCommand.Parameters.AddWithValue("MHDDatum", MHDDatum == null ? (object)DBNull.Value : MHDDatum);
				sqlCommand.Parameters.AddWithValue("inspector", inspector == null ? "-": inspector);
				sqlCommand.Parameters.AddWithValue("remarks", remarks == null ? "-": remarks);
				var result = DbExecution.ExecuteScalar(sqlCommand);
				return result == null ? int.MinValue : int.TryParse(result.ToString(), out var insertedId) ? insertedId : int.MinValue;
			}
		}
		public static Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity GetByVerpackungNrTn(int id)
		{
			var dataTable = new DataTable();
			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			using(var sqlCommand = new SqlCommand("select * from [PSZ_Eingangskontrolle_TN]  where  [Nummer Verpackung]=@Id", sqlConnection))
			{
				sqlConnection.Open();
				sqlCommand.Parameters.AddWithValue("Id", id);

				DbExecution.Fill(sqlCommand, dataTable);
			}

			if(dataTable.Rows.Count > 0)
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity(dataTable.Rows[0]);
			}
			else
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity();
			}
		}
		public static Infrastructure.Data.Entities.Tables.Logistics.PrintedDataPlantBookingEntity GetPrintDataTN(int nummerVerpackung)
		{
			var dataTable = new DataTable();
			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			using(var sqlCommand = new SqlCommand("select Top 10 Aktiv, [Nummer Verpackung], Artikelnummer,LagerortID,Menge,Gesamtmenge,Inspektor,Datum,MHDDatum,Resultat, WE_LS_VOH, [Bestellung-Nr] as WE_VOH_Nr from [PSZ_Eingangskontrolle_TN] where [Nummer Verpackung]=@Id", sqlConnection))
			{
				sqlConnection.Open();
				sqlCommand.Parameters.AddWithValue("Id", nummerVerpackung);
				DbExecution.Fill(sqlCommand, dataTable);
			}

			if(dataTable.Rows.Count > 0)
			{
				return new Infrastructure.Data.Entities.Tables.Logistics.PrintedDataPlantBookingEntity(dataTable.Rows[0], Infrastructure.Data.Entities.Tables.Logistics.LagerAccessEnum.TN);
			}
			else
			{
				return new Infrastructure.Data.Entities.Tables.Logistics.PrintedDataPlantBookingEntity();
			}
		}
		public static int UpdateWithTransaction(Infrastructure.Data.Entities.Tables.Logistics.PlantBookingUpdateEntity item, SqlConnection connection, SqlTransaction transaction)
		{
			string query = @"UPDATE [PSZ_Eingangskontrolle_TN]  SET  Aktiv = 1, Akzeptierte_Menge = @Akzeptierte_Menge, Artikelnummer = @Artikelnummer,[Clock Number] = @Clock_Number, Geprüfte_Prüfmenge = @Geprufte_Prufmenge,      Gesamtmenge = @Gesamtmenge, Inspektor = @Inspektor, Kunde = @Kunde,   Menge = @Menge,    [Laufende Nummer] = @Laufende_Nummer, Prüfentscheid = @Prufentscheid, Prüftiefe = @Pruftiefe, [Reklamierte Menge] = @Reklamierte_Menge, Resultat = @Resultat, Prüfmenge = @Prufmenge,WE_Anzahl_VOH =@WE_Anzahl_VOH WHERE [Nummer Verpackung] = @Verpackungsnr; ";

			using(var sqlCommand = new SqlCommand(query, connection, transaction))
			{
				sqlCommand.Parameters.AddWithValue("Verpackungsnr", item.Verpackungsnr);
				sqlCommand.Parameters.AddWithValue("Akzeptierte_Menge ", item.Akzeptierte_Menge == null ? (object)DBNull.Value : item.Akzeptierte_Menge);
				sqlCommand.Parameters.AddWithValue("Artikelnummer ", item.Artikelnummer == null ? (object)DBNull.Value : item.Artikelnummer);
				sqlCommand.Parameters.AddWithValue("Clock_Number ", item.Clock_Number == null ? (object)DBNull.Value : item.Clock_Number);
				sqlCommand.Parameters.AddWithValue("Geprufte_Prufmenge ", item.Geprufte_Prufmenge == null ? (object)DBNull.Value : item.Geprufte_Prufmenge);
				sqlCommand.Parameters.AddWithValue("Gesamtmenge ", item.Gesamtmenge == null ? (object)DBNull.Value : item.Gesamtmenge);
				sqlCommand.Parameters.AddWithValue("Inspektor ", item.Inspektor == null ? (object)DBNull.Value : item.Inspektor);
				sqlCommand.Parameters.AddWithValue("Kunde ", item.Kunde == null ? (object)DBNull.Value : item.Kunde);
				sqlCommand.Parameters.AddWithValue("Menge ", item.Menge == null ? (object)DBNull.Value : item.Menge);
				sqlCommand.Parameters.AddWithValue("Laufende_Nummer ", item.Laufende_Nummer == null ? (object)DBNull.Value : item.Laufende_Nummer);
				sqlCommand.Parameters.AddWithValue("Prufentscheid ", item.Prufentscheid == null ? (object)DBNull.Value : item.Prufentscheid);
				sqlCommand.Parameters.AddWithValue("Reklamierte_Menge ", item.Reklamierte_Menge == null ? (object)DBNull.Value : item.Reklamierte_Menge);
				sqlCommand.Parameters.AddWithValue("Resultat ", item.Resultat == null ? (object)DBNull.Value : item.Resultat);
				sqlCommand.Parameters.AddWithValue("Prufmenge ", item.Prufmenge == null ? (object)DBNull.Value : item.Prufmenge);
				sqlCommand.Parameters.AddWithValue("Pruftiefe ", item.Pruftiefe == null ? (object)DBNull.Value : item.Pruftiefe);
				sqlCommand.Parameters.AddWithValue("WE_Anzahl_VOH ", item.WE_Anzahl_VOH == null ? (object)DBNull.Value : item.WE_Anzahl_VOH);
				return DbExecution.ExecuteNonQuery(sqlCommand);
			}
		}


		public static int DeleteWithArtikelTn(int Id, int LagerId)
		{
			int results = -1;
			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			{
				sqlConnection.Open();
				string query = " delete from [PSZ_Eingangskontrolle_TN] where [Nummer Verpackung]=@Id AND  [LagerortID] = @LagerId";
				var sqlCommand = new SqlCommand(query, sqlConnection);
				sqlCommand.Parameters.AddWithValue("Id", Id);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId);
				results = DbExecution.ExecuteNonQuery(sqlCommand);
			}

			return results;
		}

		public static Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity GetPalntBookingsMinMaxByLagerID(int LagerID, int order)
		{
			var dataTable = new DataTable();
			

			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			{
				sqlConnection.Open();
				string query = "";
				if(order == 1)//Max
				{
					query = @"SELECT TOP 1
							*
							FROM [PSZ_Eingangskontrolle_TN]
							WHERE LagerortID = @LagerID
							ORDER BY [Nummer Verpackung] DESC";
				}
				else if(order == 2)
				{
					query = @"SELECT TOP 1
							*
							FROM [PSZ_Eingangskontrolle_TN]
							WHERE LagerortID = @LagerID
							ORDER BY [Nummer Verpackung]";
				}
				var sqlCommand = new SqlCommand(query, sqlConnection);

				sqlCommand.Parameters.AddWithValue("LagerID", LagerID);
				DbExecution.Fill(sqlCommand, dataTable);
			}
			if(dataTable.Rows.Count > 0)
			{

				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity(dataTable.Rows[0], Infrastructure.Data.Entities.Joins.Logistics.LagerAccessEnum.TN);
			}
			else
			{
		return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity();			}
		}


		public static Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity GetPlantBookingsPrecedentByLagerID(int LagerId, int PassedNmrVpckng)
		{
			var dataTable = new DataTable();

			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			{
				sqlConnection.Open();
				string query = "";
				query = @"SELECT TOP 1
					*
					FROM [PSZ_Eingangskontrolle_TN]
					WHERE LagerortID = @LagerId 
                    and [Nummer Verpackung] < @PassedNmrVpckng 
					order By [Nummer Verpackung] desc ";


				var sqlCommand = new SqlCommand(query, sqlConnection);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId);
				sqlCommand.Parameters.AddWithValue("PassedNmrVpckng", PassedNmrVpckng);

				DbExecution.Fill(sqlCommand, dataTable);
			}
			if(dataTable.Rows.Count > 0)
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity(dataTable.Rows[0], Infrastructure.Data.Entities.Joins.Logistics.LagerAccessEnum.TN);
			}
			else
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity();
			}
		}


		public static Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity GetPlantBookingsSuivantByLagerID(int LagerId, int PassedNmrVpckng)
		{
			var dataTable = new DataTable();

			using(var sqlConnection = new SqlConnection(Settings.ConnectionString))
			{
				sqlConnection.Open();
				string query = "";
			
					query = @"SELECT TOP 1
					*
					FROM [PSZ_Eingangskontrolle_TN]
					WHERE LagerortID = @LagerId 
                    and [Nummer Verpackung] > @PassedNmrVpckng 
					order By [Nummer Verpackung] asc ";
							
				var sqlCommand = new SqlCommand(query, sqlConnection);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId);
				sqlCommand.Parameters.AddWithValue("PassedNmrVpckng", PassedNmrVpckng);

				DbExecution.Fill(sqlCommand, dataTable);
			}
			if(dataTable.Rows.Count > 0)
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity(dataTable.Rows[0], Infrastructure.Data.Entities.Joins.Logistics.LagerAccessEnum.TN);
			}
			else
			{
				return new Infrastructure.Data.Entities.Joins.Logistics.PSZ_Eingangskontrolle_TNEntity();
			}
		}

		public static decimal GetAnzahlNach(int LagerId, int WereingangId,int ID)
		{
			var dataTable = new DataTable();

			using(var sqlConnection = new SqlConnection(Infrastructure.Data.Access.Settings.ConnectionString))
			{
				sqlConnection.Open();

				string query = @"SELECT SUM(l.Anzahl_nach) AS Anzahl_nach FROM Bestellungen B
					INNER JOIN [bestellte Artikel] BA ON BA.[Bestellung-Nr] = B.Nr
					INNER JOIN Artikel A ON A.[Artikel-Nr] = BA.[Artikel-Nr]
					INNER JOIN Bestellnummern BE ON B.[Lieferanten-Nr] = BE.[Lieferanten-Nr]
					INNER JOIN Lagerbewegungen_Artikel l ON l.WereingangId = BA.Nr
					AND A.[Artikel-Nr] = BE.[Artikel-Nr]   
					AND l.WereingangId = @WereingangId
					AND l.lager_nach = @LagerId
					GROUP BY  l.[WereingangId] , l.ID 
					Having l.ID=@ID";

				var sqlCommand = new SqlCommand(query, sqlConnection);
				sqlCommand.Parameters.AddWithValue("LagerId", LagerId);
				sqlCommand.Parameters.AddWithValue("WereingangId", WereingangId);
				sqlCommand.Parameters.AddWithValue("ID", ID);

				DbExecution.Fill(sqlCommand, dataTable);
			}

			if(dataTable.Rows.Count > 0)
			{
				return (dataTable.Rows[0]["Anzahl_nach"] == System.DBNull.Value) ? 0 : Convert.ToDecimal(dataTable.Rows[0]["Anzahl_nach"]);
			}
			else
			{
				return 0;
			}
		}
		#endregion
	}
}
