using Org.BouncyCastle.Asn1.Ocsp;
using Psz.Core.BaseData.Helpers;
using Psz.Core.BaseData.Models.Article.ROH.OfferRequests;
using Psz.Core.Common.Models;
using Psz.Core.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;
namespace Psz.Core.BaseData.Handlers.ROH.OfferRequests;

public class EditEmailContentForOfferRequestHandler: IHandle<Identity.Models.UserModel, ResponseModel<int>>
{
	private Identity.Models.UserModel _user { get; set; }
	private EditOfferRequestEMail _data { get; set; }
	public EditEmailContentForOfferRequestHandler(Identity.Models.UserModel user, EditOfferRequestEMail emailtoedit)
	{
		this._user = user;
		this._data = emailtoedit;
	}

	public ResponseModel<int> Handle()
	{
		var botransaction = new Infrastructure.Services.Utils.TransactionsManager();

		try
		{


			var validationResponse = this.Validate();
			if(!validationResponse.Success)
			{
				return validationResponse;
			}
			botransaction.beginTransaction();

			var fetchedOffers = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(_data.Ids);

			var offerfamily = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.UpdateOfferRequestEmailContentStatus(_data.Ids, SpecialHelper.ReplacePTagsWithDiv(_data.EmailContent), _data.EmailSubject, _data.CCEmail, _data.Recipient, _data.AdditionalCC, botransaction.connection, botransaction.transaction);

			var OldData = new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsEntity() {
				AdditionalCC = fetchedOffers.First().AdditionalCC,
				AutogeneratedEmailContent = fetchedOffers.First().AutogeneratedEmailContent,
				CCEmail = fetchedOffers.First().CCEmail,
				LatestEmailContent = fetchedOffers.First().LatestEmailContent,
				EmailSubject = fetchedOffers.First().EmailSubject,
				ManufactuerNumber = fetchedOffers.First().ManufactuerNumber,
				SupplierContactName = fetchedOffers.First().SupplierContactName,
				SupplierContactEmail = fetchedOffers.First().SupplierContactEmail,
				SupplierName = fetchedOffers.First().SupplierName
			};
			var NewData = new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsEntity() {
				AdditionalCC = _data.AdditionalCC,
				AutogeneratedEmailContent = fetchedOffers.First().AutogeneratedEmailContent,
				CCEmail = _data.CCEmail,
				LatestEmailContent = _data.EmailContent,
				EmailSubject = _data.EmailSubject,
				ManufactuerNumber = fetchedOffers.First().ManufactuerNumber,
				SupplierContactName = fetchedOffers.First().SupplierContactName,
				SupplierContactEmail = _data.Recipient,
				SupplierName = fetchedOffers.First().SupplierName
			};

			var LogSavingResult = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsAccess.InsertWithTransaction(GenerateEmailChangesLog(_data.Ids, OldData, NewData), botransaction.connection, botransaction.transaction);

			if(botransaction.commit())
			{
				return ResponseModel<int>.SuccessResponse(offerfamily);
			}
			else
			{
				return ResponseModel<int>.FailureResponse("Saving Data Failed !");
			}

		} catch(Exception e)
		{
			botransaction.rollback();
			Infrastructure.Services.Logging.Logger.Log(e);
			throw;
		}
	}

	public ResponseModel<int> Validate()
	{
		if(this._user == null /*|| this._user.Access.____*/)
		{
			return ResponseModel<int>.AccessDeniedResponse();
		}
		return ResponseModel<int>.SuccessResponse();
	}


	private List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity> GenerateEmailChangesLog(List<int> Ids, Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsEntity oldE, Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsEntity new_E)
	{
		var Logs = new List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity>();
		var offerEnities = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(Ids);

		foreach(var Id in offerEnities)
		{
			if(oldE.EmailSubject != new_E.EmailSubject)
			{
				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request Email Subject has been updated From [{oldE.EmailSubject}] to  [{new_E.EmailSubject}]",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});
			}
			if(oldE.CCEmail != new_E.CCEmail)
			{
				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request CCEmail has been updated From [{oldE.CCEmail}] to  [{new_E.CCEmail}]",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});
			}
			if(oldE.AdditionalCC != new_E.AdditionalCC)
			{
				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request Additional CCs has been updated From [{oldE.AdditionalCC}] to  [{new_E.AdditionalCC}]",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});
			}
			if(oldE.SupplierContactEmail != new_E.SupplierContactEmail)
			{
				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request Supplier Contact Email has been updated From [{oldE.SupplierContactEmail}] to  [{new_E.SupplierContactEmail}]",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});
			}
			if(oldE.LatestEmailContent == null || string.IsNullOrWhiteSpace(oldE.LatestEmailContent))
			{
				var oldEmailContent = oldE.AutogeneratedEmailContent == null ? string.Empty : oldE.AutogeneratedEmailContent.Substring(250);
				var NewEmailContent = new_E.LatestEmailContent == null ? string.Empty : new_E.LatestEmailContent.Substring(250);

				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request Email Body has been updated ",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});
			}
			else
			{
				var oldEmailContent = oldE.LatestEmailContent == null ? string.Empty : oldE.LatestEmailContent.Substring(250);
				var NewEmailContent = new_E.LatestEmailContent == null ? string.Empty : new_E.LatestEmailContent.Substring(250);

				Logs.Add(new Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.__BSD_Offer_Request_LogsEntity()
				{
					LastUpdateUserId = _user.Id,
					LastUpdateUsername = _user.Username,
					LastUpdateTime = DateTime.Now,
					LastUpdateUserFullName = _user.Name,
					LogDescription = $"The Offer request Email Body has been updated ",
					LogObjectId = Id.Id,
					ManufacturerNumber = Id.ManufactuerNumber,
					SupplierContactName = Id.SupplierContactName,
					LogObject = "BSD Offer Request"
				});

			}
		}
		return Logs;
	}


}
