using Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests;
using Org.BouncyCastle.Asn1.Ocsp;
using Psz.Core.BaseData.Models.Article.ROH.OfferRequests;
using Psz.Core.Common.Models;
using Psz.Core.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Psz.Core.BaseData.Handlers.ROH.OfferRequests
{
	public class GetEMailForOfferRequestByIdsForSingleSupplierHandler: IHandle<Identity.Models.UserModel, ResponseModel<OfferRequestEMail>>
	{
		private Identity.Models.UserModel _user { get; set; }
		private List<int> _data { get; set; }
		public GetEMailForOfferRequestByIdsForSingleSupplierHandler(Identity.Models.UserModel user, List<int> Id)
		{
			this._user = user;
			this._data = Id;
		}

		public ResponseModel<OfferRequestEMail> Handle()
		{
			try
			{
				var validationResponse = this.Validate();
				if(!validationResponse.Success)
				{
					return validationResponse;
				}
				var offerfamily = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(_data.First());

				var AllSimilarEmails = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.Get(_data);

				if(offerfamily is null)
					return ResponseModel<OfferRequestEMail>.NotFoundResponse();

				var restoreturn = new OfferRequestEMail()
				{
					CCEmail = offerfamily.CCEmail,
					EmailSubject = offerfamily.EmailSubject,
					Recipient = offerfamily.SupplierContactEmail,
					EmailContent = IsValidEmailContent(offerfamily.LatestEmailContent) ? offerfamily.LatestEmailContent : offerfamily.AutogeneratedEmailContent,
					Ids = _data,
					AdditionalCC = offerfamily.AdditionalCC,
			    };
				restoreturn.MaterialTable  = GenerateEmailSubjectBasedOnDefaultSupplierLanguage(Infrastructure.Services.Helpers.EmailHelper.GetLanguageBasedOnEmailBody(restoreturn.EmailContent) ,AllSimilarEmails);
				return ResponseModel<OfferRequestEMail>.SuccessResponse(restoreturn);
			} catch(Exception e)
			{
				Infrastructure.Services.Logging.Logger.Log(e);
				throw;
			}
		}
		//GetLanguageBasedOnEmailBody


		private string GenerateEmailSubjectBasedOnDefaultSupplierLanguage(int supplierID, List<ArticleOfferRequestsEntity> allOfferForOneSupplier)
		{

			if(supplierID <= 0)
				supplierID = 4;

			var emailBody = supplierID switch
			{
				1 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialTable_EN(Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(allOfferForOneSupplier)),
				2 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialTable_FR(Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(allOfferForOneSupplier)),
				3 => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialTable_SP(Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(allOfferForOneSupplier)),
				_ => Infrastructure.Services.Helpers.EmailHelper.GenerateMaterialTable_DE(Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(allOfferForOneSupplier))
			};
			return emailBody;
		}

		private bool IsValidEmailContent(string content)
		{
			return !(string.IsNullOrEmpty(content) || string.IsNullOrWhiteSpace(content));
		}
		public ResponseModel<OfferRequestEMail> Validate()
		{
			if(this._user == null /*|| this._user.Access.____*/)
			{
				return ResponseModel<OfferRequestEMail>.AccessDeniedResponse();
			}
			return ResponseModel<OfferRequestEMail>.SuccessResponse();
		}
	}
}
