using Org.BouncyCastle.Asn1.Ocsp;
using Psz.Core.BaseData.Helpers;
using Psz.Core.BaseData.Models.Article.ROH.OfferRequests;
using Psz.Core.Common.Models;
using Psz.Core.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Psz.Core.BaseData.Handlers.ROH.OfferRequests
{
	public class GetOfferRequestEmailPerRequestUIHandler: IHandle<Identity.Models.UserModel, ResponseModel<List<OfferRequestEMail>>>
	{
		private Identity.Models.UserModel _user { get; set; }
		private string _data { get; set; }
		public GetOfferRequestEmailPerRequestUIHandler(Identity.Models.UserModel user, string RequestUI)
		{
			this._user = user;
			this._data = RequestUI;
		}

		public ResponseModel<List<OfferRequestEMail>> Handle()
		{
			try
			{


				var validationResponse = this.Validate();
				if(!validationResponse.Success)
				{
					return validationResponse;
				}
				var offerfamily = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUI(_data);


				if(offerfamily is null || offerfamily.Count == 0)
					return ResponseModel<List<OfferRequestEMail>>.FailureResponse("Sorry, Offer  not found !.");

				var offerrequestsPerSupplier = new List<OfferRequestPerSupplierModel>();

				var uniqueSuppliers = offerfamily.Select(x => x.SupplierId).Distinct().ToList();

				var offerRequestsSlicedUponUniqueSuppliers = new List<OfferRequestPerSupplierModel>();


				var restoreturn = new List<OfferRequestEMail>();
				int index = 1;
				foreach(var item in uniqueSuppliers)
				{
					var email = new OfferRequestEMail();
					var fetchedIds = Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.ArticleOfferRequestsAccess.GetByRequestUIAndSupplierID(_data, item);

					// Add the List Of Ids that has the same Supplier
					email.Ids = fetchedIds.Select(x => x.Id).ToList();
					email.index = index;
					// get Default recipient 
					email.Recipient = fetchedIds.First().SupplierContactEmail;
					// get Default CC EMAIL 
					email.CCEmail = fetchedIds.First().CCEmail;

					email.ProjectName = fetchedIds.First().ProjectName;
					email.EndCustomer = fetchedIds.First().EndCustomer;
					email.EmailSubject = fetchedIds.First().EmailSubject;
					email.AdditionalCC = fetchedIds.First().AdditionalCC;
					email.EmailSent = fetchedIds.First().EmailStatus ?? false;
					#region Get Email Attachments
					var attchments = GetAttachmentsIds(fetchedIds.Select(x => x.Id).Distinct().ToList());
						if(attchments is not null && attchments.Count >0)
						{
							email.attachments = attchments.Select(x => new Attachments() { FiledId = (int)x.FileId ,FileName = x.FileName }).ToList();
						}
						else
						{
							email.attachments = new List<Attachments>();
						}
					#endregion 
					var dataforEmail = Psz.Core.BaseData.Helpers.SpecialHelper.GenerateMaterials(fetchedIds);
					// use the quantites and material to generate the needed Data for the email body . 
					if(fetchedIds.First().LatestEmailContent is not null && !string.IsNullOrWhiteSpace(fetchedIds.First().LatestEmailContent))
					{
						email.EmailContent = Infrastructure.Services.Helpers.EmailHelper.AddMaterialTableToTheEmail(dataforEmail, fetchedIds.First().LatestEmailContent);
					}
					else
					{
						email.EmailContent = Infrastructure.Services.Helpers.EmailHelper.AddMaterialTableToTheEmail(dataforEmail, fetchedIds.First().AutogeneratedEmailContent);

					}
					email.multipleSuppliers = fetchedIds.Count() > 1 ? true : false;

					//return the request UI
					email.RequestUI = _data;
					restoreturn.Add(email);

					index++;
				}
				return ResponseModel<List<OfferRequestEMail>>.SuccessResponse(restoreturn);
			} catch(Exception e)
			{
				Infrastructure.Services.Logging.Logger.Log(e);
				throw;
			}
		}
		private bool AttachmentExists(int? attachmentId)
		{
			if(attachmentId is null || attachmentId <= 0)
				return false;
			else
				return true;
		}
		private List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsEntity> GetAttachmentsIds(List<int> OffersIds)
		{
			try
			{
				return Infrastructure.Data.Access.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsAccess.GetAttachmentsPerOffers(OffersIds);

			} catch(Exception e)
			{
				Infrastructure.Services.Logging.Logger.Log(e);
			}
			return new List<Infrastructure.Data.Entities.Tables.BSD.ROH.OfferRequests.OfferRequestEmailAttachmentsEntity>();
		}
		public ResponseModel<List<OfferRequestEMail>> Validate()
		{
			if(this._user == null /*|| this._user.Access.____*/)
			{
				return ResponseModel<List<OfferRequestEMail>>.AccessDeniedResponse();
			}
			return ResponseModel<List<OfferRequestEMail>>.SuccessResponse();
		}
	}
}
