using System;

namespace Psz.Core.BaseData.Models.Article
{
	public class ArticleSalesModel
	{
		public DateTime? Gepackt_Zeitpunkt { get; set; }
		public DateTime? Liefertermin { get; set; }
		public DateTime? Versanddatum_Auswahl { get; set; }
		public DateTime? Wunschtermin { get; set; }

		public int? ABPoszuBVPos { get; set; }
		public int? ABPoszuRAPos { get; set; }
		public string Abladestelle { get; set; }
		public double? AktuelleAnzahl { get; set; }
		public double? AnfangLagerBestand { get; set; }
		public int? AngebotNr { get; set; }
		public double? Anzahl { get; set; }
		public int? ArtikelNr { get; set; }
		public bool? Auswahl { get; set; }
		public string Bemerkungsfeld1 { get; set; }
		public string Bemerkungsfeld2 { get; set; }
		public string Bestellnummer { get; set; }
		public string Bezeichnung1 { get; set; }
		public string Bezeichnung2 { get; set; }
		public string Bezeichnung2_Kunde { get; set; }
		public string Bezeichnung3 { get; set; }
		public int? DEL { get; set; }
		public bool? DELFixiert { get; set; }
		public int? EDI_Historie_Nr { get; set; }
		public double? EDI_PREIS_KUNDE { get; set; }
		public double? EDI_PREISEINHEIT { get; set; }
		public double? EDI_Quantity_Ordered { get; set; }
		public string Einheit { get; set; }
		public double? EinzelCuGewicht { get; set; }
		public double? Einzelkupferzuschlag { get; set; }
		public double? Einzelpreis { get; set; }
		public bool? EKPreise_Fix { get; set; }
		public double? EndeLagerBestand { get; set; }
		public bool? erledigt_pos { get; set; }
		public int? Fertigungsnummer { get; set; }
		public string FM { get; set; }
		public double? FM_Einzelpreis { get; set; }
		public double? FM_Gesamtpreis { get; set; }
		public string Freies_Format_EDI { get; set; }
		public double? Geliefert { get; set; }
		public string Gepackt_von { get; set; }
		public double? GesamtCuGewicht { get; set; }
		public double? Gesamtkupferzuschlag { get; set; }
		public double? Gesamtpreis { get; set; }
		public bool? InBearbeitung { get; set; }
		public int? KBPoszuBVPos { get; set; }
		public int? KBPoszuRAPos { get; set; }
		public int? Kupferbasis { get; set; }
		public bool? Lagerbewegung { get; set; }
		public bool? Lagerbewegung_rückgängig { get; set; }
		public int? Lagerort_id { get; set; }
		public string Langtext { get; set; }
		public bool? Langtext_drucken { get; set; }
		public string LieferanweisungP_FTXDIN_TEXT { get; set; }
		public bool? Loschen { get; set; }
		public int? LSPoszuABPos { get; set; }
		public int? LSPoszuKBPos { get; set; }
		public bool? LS_von_Versand_gedruckt { get; set; }
		public int Nr { get; set; }
		public double? OriginalAnzahl { get; set; }
		public string Packinfo_von_Lager { get; set; }
		public bool? Packstatus { get; set; }
		public int? Position { get; set; }
		public int? PositionZUEDI { get; set; }
		public string POSTEXT { get; set; }
		public bool? Preis_ausweisen { get; set; }
		public double? Preiseinheit { get; set; }
		public int? Preisgruppe { get; set; }
		public int? RAPoszuBVPos { get; set; }
		public double? RA_Abgerufen { get; set; }
		public double? RA_Offen { get; set; }
		public double? RA_OriginalAnzahl { get; set; }
		public double? Rabatt { get; set; }
		public bool? RP { get; set; }
		public string schriftart { get; set; }
		public bool? Seriennummern_drucken { get; set; }
		public string sortierung { get; set; }
		public bool? Stückliste { get; set; }
		public bool? Stückliste_drucken { get; set; }
		public bool? Summenberechnung { get; set; }
		public bool? termin_eingehalten { get; set; }
		public ulong? upssize_ts { get; set; }
		public double? USt { get; set; }
		public bool? VDA_gedruckt { get; set; }
		public bool? Versand_gedruckt { get; set; }
		public string Versandarten_Auswahl { get; set; }
		public string Versanddienstleister { get; set; }
		public string Versandinfo_von_CS { get; set; }
		public string Versandinfo_von_Lager { get; set; }
		public string Versandnummer { get; set; }
		public bool? Versandstatus { get; set; }
		public double? VKEinzelpreis { get; set; }
		public bool? VKFestpreis { get; set; }
		public double? VKGesamtpreis { get; set; }
		public string Zeichnungsnummer { get; set; }
		public string zwischensumme { get; set; }
		public int? Typ { get; set; }
	}
}
