using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using Psz.Api;
using Psz.Api.Extensions;
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseWindowsService();
builder.Services.AddWindowsService();
var startup = new Startup(builder.Configuration, builder.Environment);
startup.ConfigureServices(builder.Services);
builder.Services.AddOpenTelemetryERP();
var app = builder.Build();
app.UseOpenTelemetryPrometheusScrapingEndpoint();
startup.Configure(app, builder.Environment);
app.Run();
