steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        # Cette commande cherche automatiquement votre fichier .sln ou .csproj
        run: dotnet restore **/*.sln 

      - name: Build
        # Idem pour la compilation
        run: dotnet build **/*.sln --no-restore
